version: 2
jobs:
  build:
    working_directory: ~/serverlesshelloworld
    docker:
      # specify the version you desire here
      - image: circleci/node:10.1.0

    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
            
      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy -v
